/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class project_weatherforecast_CustomNDK */

#ifndef _Included_project_weatherforecast_CustomNDK
#define _Included_project_weatherforecast_CustomNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     project_weatherforecast_CustomNDK
 * Method:    convert_temperature
 * Signature: (DI)D
 */
JNIEXPORT jdouble JNICALL Java_project_weatherforecast_CustomNDK_convert_1temperature
  (JNIEnv *, jobject, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
